# This file was generated by GoReleaser. DO NOT EDIT.
class Sampctl < Formula
  desc "The Swiss Army Knife of SA:MP - vital tools for any server owner or library maintainer."
  homepage "https://github.com/Southclaws/sampctl"
  url "https://github.com/Southclaws/sampctl/releases/download/1.8.38/sampctl_1.8.38_darwin_amd64.tar.gz"
  version "1.8.38"
  sha256 "55093200666a4f3bef77482a00a486a41424e08d07c28c1b137a111766a94fb9"

  def install
    bin.install "sampctl"
  end
end
